// bin/template/react/react-router/vanilla-extract/app/components/layout/card/card.tsx
import cardStyles from "./card.css";
import type { CheckerProps } from "@/shared/types/object";
import type { CSSProperties } from "react";

interface Props {
    key: number | string;
    title: string;
    src: string;
    alt: string;
    boxHeight: number;
    srcWidth: number;
    srcHeight: number;
}

export function Card<T extends Props>(
    props: CheckerProps<T, Props, "different card props">
) {
    const { title, src, alt, srcWidth, srcHeight, boxHeight } = props;

    const cardStyle: CSSProperties = {
        width: srcWidth,
        height: boxHeight
    };

    return (
        <div className={cardStyles.cardContainer} style={cardStyle}>
            <img
                src={src}
                alt={alt}
                className={cardStyles.image}
                width={srcWidth}
                height={srcHeight}
            />
            <p className={cardStyles.title}>{title}</p>
        </div>
    );
}

// bin/template/vue/vue-router/vanilla-extract/src/components/layout/card/card.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'
import cardStyle from './card.css'

const { title, src, alt, boxHeight, srcWidth, srcHeight } = defineProps<{
  title: string
  src: string
  alt: string
  boxHeight: number
  srcWidth: number
  srcHeight: number
}>()

const boxStyle: CSSProperties = {
  height: `${boxHeight}px`,
  width: `${srcWidth}px`,
}
</script>

<template>
  <div :class="cardStyle.cardContainer" :style="boxStyle">
    <img :class="cardStyle.image" :src="src" :alt="alt" :width="srcWidth" :height="srcHeight" />
    <p :class="cardStyle.title">{{ title }}</p>
  </div>
</template>
