// bin/template/vue/vue-router/scoped-css/src/components/layout/card/card.vue
<script setup lang="ts">
import type { CSSProperties } from 'vue'

const { title, src, alt, boxHeight, srcWidth, srcHeight } = defineProps<{
  title: string
  src: string
  alt: string
  boxHeight: number
  srcWidth: number
  srcHeight: number
}>()

const boxStyle: CSSProperties = {
  height: `${boxHeight}px`,
  width: `${srcWidth}px`,
}
</script>

<template>
  <div class="card-container" :style="boxStyle">
    <img class="image" :src="src" :alt="alt" :width="srcWidth" :height="srcHeight" />
    <p class="title">{{ title }}</p>
  </div>
</template>

<style scoped>
.card-container {
  border: 1px solid #ccc;
  border-radius: 10px;
  overflow: hidden;
  box-shadow: 0 4px 8px rgb(0 0 0 / 10%);
  text-align: center;
  margin: 1rem;
}

.image {
  object-fit: cover;
}

.title {
  padding: 1rem;
  font-size: 1.2rem;
  font-weight: bold;
  color: #333;
  margin: 0;
}
</style>

// packages/create-template/template/react/tanstack-router/tailwind/src/components/layout/card/card.tsx
import { Box } from '@/components/ui'
import { CheckerProps } from '@/shared/types/object'
import classMerger from '@/utils/class-merger'
import { CSSProperties } from 'react'

interface Props {
    key: number | string
    title: string
    src: string
    alt: string
    boxHeight: number
    srcWidth: number
    srcHeight: number
}

export function Card<T extends Props>(
    props: CheckerProps<T, Props, 'different card props'>,
) {
    const { title, src, alt, srcWidth, srcHeight, boxHeight } = props

    // Integrate dynamic width/height via inline style (optional: could be arbitrary Tailwind classes)
    const cardStyle: CSSProperties = { width: srcWidth, height: boxHeight }

    return (
        <Box
            className={classMerger([
                'm-[0.8rem]',
                'overflow-hidden',
                'rounded-[18px]',
                'border',
                'border-[#dbe1ea]',
                'bg-white/[0.92]',
                'text-center',
                'shadow-[0_12px_28px_rgba(15,23,42,0.12)]',
                'backdrop-blur-[6px]',
                'transition-[transform,box-shadow,border-color]',
                'duration-200',
                'ease-in',
                'hover:-translate-y-1',
                'hover:border-[#93c5fd]',
                'hover:shadow-[0_20px_36px_rgba(30,64,175,0.22)]',
            ])}
            style={cardStyle}
        >
            <img
                src={src}
                alt={alt}
                className={classMerger([
                    'w-full',
                    'border-b',
                    'border-b-slate-200',
                    'object-cover',
                ])}
                style={{ height: srcHeight }}
                width={srcWidth}
                height={srcHeight}
            />
            <p
                className={classMerger([
                    'm-0',
                    'p-[0.9rem]',
                    'text-[1rem]',
                    'font-bold',
                    'leading-[1.35]',
                    'text-slate-900',
                ])}
            >
                {title}
            </p>
        </Box>
    )
}
